name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always


# should build for windows, linux and macos and arm64 and amd64 each
# and add to releases on github

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, arm64]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install dependencies
      run: cargo build --release
#    - name: Run tests
#      run: cargo test
    - name: Build
      run: cargo build --release
    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-${{ matrix.arch }}-release
        path: target/release/
    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        files: target/release/*
        token: ${{ secrets.PAT }}
        tag_name: ${{ github.run_id }}-${{ github.run_attempt }}
